stages:
  - gen-go
  # - notify

services:
  - name: docker:20.10.12
    command: ["--tls=false"]

image: gitlab.com/public/docker:20.10.12-go1.17.5
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  TZ: "Asia/Shanghai"

before_script:
  - git config --global user.name "user"
  - git config --global user.email "devops@github.com"
  - git config pull.rebase false
  - git remote set-url origin https://${CI_USERNAME}:${CI_PASSWORD}@github.com/$CI_PROJECT_PATH.git

gen-go-stage:
  stage: gen-go
  tags:
    - develop
  script:
    - make gen-go
  only:
    - develop
  except:
    variables:
      - $GITLAB_USER_EMAIL =~ /^devops@github.com$/
