// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: user_enum.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DATA_STATUS int32

const (
	DATA_STATUS_UNIVERSAL_DATA DATA_STATUS = 0  // 默认值
	DATA_STATUS_HIDE           DATA_STATUS = 1  // 隐藏
	DATA_STATUS_ONLINE         DATA_STATUS = 2  // 线上
	DATA_STATUS_DRAFT          DATA_STATUS = 3  // 草稿
	DATA_STATUS_EXAMINE        DATA_STATUS = 4  // 审核
	DATA_STATUS_DELETE         DATA_STATUS = 99 // 删除
)

// Enum value maps for DATA_STATUS.
var (
	DATA_STATUS_name = map[int32]string{
		0:  "UNIVERSAL_DATA",
		1:  "HIDE",
		2:  "ONLINE",
		3:  "DRAFT",
		4:  "EXAMINE",
		99: "DELETE",
	}
	DATA_STATUS_value = map[string]int32{
		"UNIVERSAL_DATA": 0,
		"HIDE":           1,
		"ONLINE":         2,
		"DRAFT":          3,
		"EXAMINE":        4,
		"DELETE":         99,
	}
)

func (x DATA_STATUS) Enum() *DATA_STATUS {
	p := new(DATA_STATUS)
	*p = x
	return p
}

func (x DATA_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DATA_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[0].Descriptor()
}

func (DATA_STATUS) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[0]
}

func (x DATA_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DATA_STATUS.Descriptor instead.
func (DATA_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{0}
}

type OPERATION_STATUS int32

const (
	OPERATION_STATUS_UNIVERSAL_OPERATION OPERATION_STATUS = 0 // 默认
	OPERATION_STATUS_BEING               OPERATION_STATUS = 1 // 运营中
	OPERATION_STATUS_DISMISS             OPERATION_STATUS = 2 // 已解散
)

// Enum value maps for OPERATION_STATUS.
var (
	OPERATION_STATUS_name = map[int32]string{
		0: "UNIVERSAL_OPERATION",
		1: "BEING",
		2: "DISMISS",
	}
	OPERATION_STATUS_value = map[string]int32{
		"UNIVERSAL_OPERATION": 0,
		"BEING":               1,
		"DISMISS":             2,
	}
)

func (x OPERATION_STATUS) Enum() *OPERATION_STATUS {
	p := new(OPERATION_STATUS)
	*p = x
	return p
}

func (x OPERATION_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OPERATION_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[1].Descriptor()
}

func (OPERATION_STATUS) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[1]
}

func (x OPERATION_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OPERATION_STATUS.Descriptor instead.
func (OPERATION_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{1}
}

type TRANSFERS_STATUS int32

const (
	TRANSFERS_STATUS_UNIVERSAL_TRANSFERS TRANSFERS_STATUS = 0 // 默认值
	TRANSFERS_STATUS_UNCONFIRMED         TRANSFERS_STATUS = 1 // 网传
	TRANSFERS_STATUS_VERIFIED            TRANSFERS_STATUS = 2 // 正式
)

// Enum value maps for TRANSFERS_STATUS.
var (
	TRANSFERS_STATUS_name = map[int32]string{
		0: "UNIVERSAL_TRANSFERS",
		1: "UNCONFIRMED",
		2: "VERIFIED",
	}
	TRANSFERS_STATUS_value = map[string]int32{
		"UNIVERSAL_TRANSFERS": 0,
		"UNCONFIRMED":         1,
		"VERIFIED":            2,
	}
)

func (x TRANSFERS_STATUS) Enum() *TRANSFERS_STATUS {
	p := new(TRANSFERS_STATUS)
	*p = x
	return p
}

func (x TRANSFERS_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TRANSFERS_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[2].Descriptor()
}

func (TRANSFERS_STATUS) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[2]
}

func (x TRANSFERS_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TRANSFERS_STATUS.Descriptor instead.
func (TRANSFERS_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{2}
}

var File_user_enum_proto protoreflect.FileDescriptor

var file_user_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x2a, 0x5b, 0x0a, 0x0b, 0x44, 0x41, 0x54, 0x41, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x49, 0x56, 0x45, 0x52,
	0x53, 0x41, 0x4c, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49,
	0x44, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45,
	0x58, 0x41, 0x4d, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x63, 0x2a, 0x43, 0x0a, 0x10, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x49, 0x56,
	0x45, 0x52, 0x53, 0x41, 0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x45, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x49, 0x53, 0x4d, 0x49, 0x53, 0x53, 0x10, 0x02, 0x2a, 0x4a, 0x0a, 0x10, 0x54, 0x52, 0x41,
	0x4e, 0x53, 0x46, 0x45, 0x52, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x17, 0x0a,
	0x13, 0x55, 0x4e, 0x49, 0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x46, 0x45, 0x52, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x52, 0x4d, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x45, 0x52, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x69, 0x71, 0x69, 0x61, 0x6e, 0x67, 0x78, 0x75, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x3b, 0x75, 0x73, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_enum_proto_rawDescOnce sync.Once
	file_user_enum_proto_rawDescData = file_user_enum_proto_rawDesc
)

func file_user_enum_proto_rawDescGZIP() []byte {
	file_user_enum_proto_rawDescOnce.Do(func() {
		file_user_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_enum_proto_rawDescData)
	})
	return file_user_enum_proto_rawDescData
}

var file_user_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_user_enum_proto_goTypes = []interface{}{
	(DATA_STATUS)(0),      // 0: user.DATA_STATUS
	(OPERATION_STATUS)(0), // 1: user.OPERATION_STATUS
	(TRANSFERS_STATUS)(0), // 2: user.TRANSFERS_STATUS
}
var file_user_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_enum_proto_init() }
func file_user_enum_proto_init() {
	if File_user_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_enum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_enum_proto_goTypes,
		DependencyIndexes: file_user_enum_proto_depIdxs,
		EnumInfos:         file_user_enum_proto_enumTypes,
	}.Build()
	File_user_enum_proto = out.File
	file_user_enum_proto_rawDesc = nil
	file_user_enum_proto_goTypes = nil
	file_user_enum_proto_depIdxs = nil
}
